spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false # Zuul'ul kendi load balancer'ını kullanmak için

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    personnel-service:
      path: /personnel-service/**
      serviceId: personnel-service  # Zuul tarafından kulanılacak proxy'ler
    user-service:
      path: /user-service/**
      serviceId: user-service
  host:
    connect-timeout-millis: 10000
    connection-request-timeout-millis: 10000
    socket-timeout-millis: 10000

api:
  registration:
    url:
      path: /user-service/users
  login:
    url:
      path: /user-service/users/login
  users:
    actuator:
      url:
        path: /user-service/actuator/*

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

token:
  secret: hfgry463hf746hf573ydh475fhy5739